version: 2
jobs:
    build:
        working_directory: ~/semantic-release-docker-aot
        docker:
            - image: circleci/node:9.5.0
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                name: register-myget
                command: echo -e "registry=https://www.myget.org/F/adsontop-packages/npm/\nalways-auth=true\n//www.myget.org/F/adsontop-packages/npm/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                name: install-deps
                command: yarn
            - save_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - persist_to_workspace:
                root: ./
                paths:
                    - ./node_modules
            - run:
                name: lint
                command: yarn lint
            - run:
                name: build
                command: yarn build
    release:
        working_directory: ~/semantic-release-docker-aot
        docker:
            - image: kbambridge/circleci-node-awscli:9
              environment:
                TERM: dumb
        steps:
            - checkout
            - setup_remote_docker
            - attach_workspace:
                at: ./
            - run:
                name: Run aws login
                command: eval $(aws ecr get-login --region us-west-1 --no-include-email)
            - run:
                name: register-myget
                command: echo -e "registry=https://www.myget.org/F/adsontop-packages/npm/\nalways-auth=true\n//www.myget.org/F/adsontop-packages/npm/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                name: Run Semantic Release
                command: yarn semantic-release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: org-global
      - release:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master
